# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2020-02-05 06:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0024_product_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='user_quantity',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='productseller',
            name='price',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=20),
        ),
    ]
