# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2020-02-05 20:00
from __future__ import unicode_literals

from django.db import migrations
import taggit.managers


class Migration(migrations.Migration):

    dependencies = [
        ('taggit', '0003_taggeditem_add_unique_index'),
        ('products', '0025_auto_20200204_2253'),
    ]

    operations = [
        migrations.AddField(
            model_name='productcategories',
            name='tags',
            field=taggit.managers.TaggableManager(help_text='A comma-separated list of tags.', through='taggit.TaggedItem', to='taggit.Tag', verbose_name='Tags'),
        ),
    ]
